In [4]:
import numpy as np 
import pandas as pd

In [50]:
#load file for all dates
data_filepath = 'Verbose.csv'
df_data = pd.read_csv(data_filepath)
df_data

/var/folders/6m/87kslmb13vl09hjpjjpddb2h0000gn/T/ipykernel_59820/211380307.py:3: DtypeWarning: Columns (14,22,30) have mixed types. Specify dtype option on import or set low_memory=False.
  df_data = pd.read_csv(data_filepath)

,State Code,County Code,Site ID,Parameter,POC,Sample Duration,Unit,Method,Date,Start Time,...,SiteName,ParamMethod,AnalysisDescription,ParameterName,ChemicalFormula,dt,Sample End Time,Qualifier 1 Description,Qualifier 2 Description,Qualifier 3 Description
0,49.0,11.0,4.0,43102.0,1.0,1.0,78.0,228.0,20241001.0,00:00,...,NaN,43102.0228,NaN,NaN,NaN,2024-10-01 00:00:00,2024-10-01 01:00:00,NaN,NaN,NaN
1,49.0,11.0,4.0,43102.0,1.0,1.0,78.0,228.0,20241001.0,01:00,...,NaN,43102.0228,NaN,NaN,NaN,2024-10-01 01:00:00,2024-10-01 02:00:00,NaN,NaN,NaN
2,49.0,11.0,4.0,43102.0,1.0,1.0,78.0,228.0,20241001.0,02:00,...,NaN,43102.0228,NaN,NaN,NaN,2024-10-01 02:00:00,2024-10-01 03:00:00,NaN,NaN,NaN
3,49.0,11.0,4.0,43102.0,1.0,1.0,78.0,228.0,20241001.0,03:00,...,NaN,43102.0228,NaN,NaN,NaN,2024-10-01 03:00:00,2024-10-01 04:00:00,NaN,NaN,NaN
4,49.0,11.0,4.0,43102.0,1.0,1.0,78.0,228.0,20241001.0,04:00,...,NaN,43102.0228,NaN,NaN,NaN,2024-10-01 04:00:00,2024-10-01 05:00:00,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1614013,49.0,45.0,4.0,45225.0,1.0,1.0,78.0,228.0,20250228.0,20:00,...,NaN,45225.0228,NaN,NaN,NaN,2025-02-28 20:00:00,2025-02-28 21:00:00,Analyte Identified; Reported Value May Be Bias...,Value less than MDL.,NaN
1614014,49.0,45.0,4.0,45225.0,1.0,1.0,78.0,228.0,20250228.0,21:00,...,NaN,45225.0228,NaN,NaN,NaN,2025-02-28 21:00:00,2025-02-28 22:00:00,Analyte Identified; Reported Value May Be Bias...,Value less than MDL.,NaN
1614015,49.0,45.0,4.0,45225.0,1.0,1.0,78.0,228.0,20250228.0,22:00,...,NaN,45225.0228,NaN,NaN,NaN,2025-02-28 22:00:00,2025-02-28 23:00:00,Analyte Identified; Reported Value May Be Bias...,Value less than MDL.,NaN
1614016,49.0,45.0,4.0,45225.0,1.0,1.0,78.0,228.0,20250228.0,23:00,...,NaN,45225.0228,NaN,NaN,NaN,2025-02-28 23:00:00,2025-03-01 00:00:00,Analyte Identified; Reported Value May Be Bias...,Value less than MDL.,NaN
1614017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,nannan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_hawthorne_usos_only = df_data.loc[(df_data['StationSym'] == 'HW')] #Get only the data at Hawthorne
#set index to datetimeindex
df_hawthorne_usos_only.set_index(['dt'], inplace = True) 
df_hawthorne_usos_only.index = pd.to_datetime(df_hawthorne_usos_only.index)

#Get only the data during the USOS campaign
df_hawthorne_usos_only = df_hawthorne_usos_only.sort_index().loc['2024-07-14 00:00:00':'2024-08-18 23:00:00']

In [65]:
df_hawthorne_usos_only

,State Code,County Code,Site ID,Parameter,POC,Sample Duration,Unit,Method,Date,Start Time,...,Longitude,SiteName,ParamMethod,AnalysisDescription,ParameterName,ChemicalFormula,Sample End Time,Qualifier 1 Description,Qualifier 2 Description,Qualifier 3 Description
dt,,,,,,,,,,,,,,,,,,,,,
2024-07-14 00:00:00,49.0,35.0,3006.0,43214.0,1.0,1.0,78.0,228.0,20240714.0,00:00,...,-111.872222,NaN,43214.0228,NaN,NaN,NaN,2024-07-14 01:00:00,NaN,NaN,NaN
2024-07-14 00:00:00,49.0,35.0,3006.0,45201.0,1.0,1.0,78.0,228.0,20240714.0,00:00,...,-111.872222,NaN,45201.0228,NaN,NaN,NaN,2024-07-14 01:00:00,NaN,NaN,NaN
2024-07-14 00:00:00,49.0,35.0,3006.0,45210.0,1.0,1.0,78.0,228.0,20240714.0,00:00,...,-111.872222,NaN,45210.0228,NaN,NaN,NaN,2024-07-14 01:00:00,NaN,NaN,NaN
2024-07-14 00:00:00,49.0,35.0,3006.0,43248.0,1.0,1.0,78.0,228.0,20240714.0,00:00,...,-111.872222,NaN,43248.0228,NaN,NaN,NaN,2024-07-14 01:00:00,NaN,NaN,NaN
2024-07-14 00:00:00,49.0,35.0,3006.0,43226.0,1.0,1.0,78.0,228.0,20240714.0,00:00,...,-111.872222,NaN,43226.0228,NaN,NaN,NaN,2024-07-14 01:00:00,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-08-18 23:00:00,49.0,35.0,3006.0,43230.0,1.0,1.0,78.0,228.0,20240818.0,23:00,...,-111.872222,NaN,43230.0228,NaN,NaN,NaN,2024-08-19 00:00:00,Values Between SQL and MDL.,NaN,NaN
2024-08-18 23:00:00,49.0,35.0,3006.0,43248.0,1.0,1.0,78.0,228.0,20240818.0,23:00,...,-111.872222,NaN,43248.0228,NaN,NaN,NaN,2024-08-19 00:00:00,"No Value Detected, Zero Reported.",Value less than MDL.,NaN
2024-08-18 23:00:00,49.0,35.0,3006.0,43242.0,1.0,1.0,78.0,228.0,20240818.0,23:00,...,-111.872222,NaN,43242.0228,NaN,NaN,NaN,2024-08-19 00:00:00,"No Value Detected, Zero Reported.",Value less than MDL.,NaN
2024-08-18 23:00:00,49.0,35.0,3006.0,45218.0,1.0,1.0,78.0,228.0,20240818.0,23:00,...,-111.872222,NaN,45218.0228,NaN,NaN,NaN,2024-08-19 00:00:00,NaN,NaN,NaN
2024-08-18 23:00:00,49.0,35.0,3006.0,45220.0,1.0,1.0,78.0,228.0,20240818.0,23:00,...,-111.872222,NaN,45220.0228,NaN,NaN,NaN,2024-08-19 00:00:00,"No Value Detected, Zero Reported.",Value less than MDL.,NaN

In [62]:
df_hawthorne_usos_only['Parameter'].unique()

array([43214., 45201., 45210., 43248., 43226., 43102., 43244., 43252.,
       43954., 43205., 45211., 43232., 43230., 43247., 45219., 45208.,
       43960., 45212., 43249., 43141., 43262., 43280., 43227., 43250.,
       45202., 43218., 43242., 43202., 43261., 43217., 45213., 43206.,
       43216., 43245., 43253., 43220., 45209., 45203., 43224., 45204.,
       45220., 43285., 43221., 43291., 43235., 43212., 43203., 43284.,
       45218., 45109., 45225., 43231., 43263., 43204., 43233., 43243.,
       43238., 45207., 43502.])

In [64]:
sorted(df_hawthorne_usos_only['Parameter'].unique())

[43102.0,
 43141.0,
 43202.0,
 43203.0,
 43204.0,
 43205.0,
 43206.0,
 43212.0,
 43214.0,
 43216.0,
 43217.0,
 43218.0,
 43220.0,
 43221.0,
 43224.0,
 43226.0,
 43227.0,
 43230.0,
 43231.0,
 43232.0,
 43233.0,
 43235.0,
 43238.0,
 43242.0,
 43243.0,
 43244.0,
 43245.0,
 43247.0,
 43248.0,
 43249.0,
 43250.0,
 43252.0,
 43253.0,
 43261.0,
 43262.0,
 43263.0,
 43280.0,
 43284.0,
 43285.0,
 43291.0,
 43502.0,
 43954.0,
 43960.0,
 45109.0,
 45201.0,
 45202.0,
 45203.0,
 45204.0,
 45207.0,
 45208.0,
 45209.0,
 45210.0,
 45211.0,
 45212.0,
 45213.0,
 45218.0,
 45219.0,
 45220.0,
 45225.0]